# This is a basic workflow to help you get started with Actions

name: ActionTut

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Step 1 - Log the pre-build disk space
        run: df -h

      - name: Step 2 Checkout the main Github branch
        uses: actions/checkout@v4

      - name: Step 3 Setup JDK
        uses: actions/setup-java@1
        with:
          java-version: 17

      - name: Step 4 - Build your jacarta web app with Maven
        run: echo mvn -B package --file pom.xml

      - name: Step 5 - Build the native Android app
        run: |
          echo Here is the ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT

      - name: Step 6 - Run your selenium test
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH

      - name: Step 7 - Log build tool version
        run: |
          git --version
          mvn --version
          ant --version
          gradle --version

      - name: Step 8 - Log the post-build disc space
        run: df -h
